services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/test-task-app
    env_file:
      - .env
    depends_on:
      - db
